### ISSUE TITLE
Is dualsense supported?

### ISSUE THREAD

**Issue by Hustwireless** [naoki-mizuno/ds4_driver#16]
Hi! Thanks for this driver! Just wondering whether does it support dualsense also?

**Comment by naoki-mizuno** [comment]
I don't have access to a DualSense, but whether or not this package works for a DualSense depends on the underlying `ds4drv`. It seems like `ds4drv` currently does not support DualSense (https://github.com/chrippa/ds4drv/issues/182) so my guess is that it won't work.

**Comment by Hustwireless** [comment]
Thanks for your rapid reply! 

I've found some news says sony has added dualsense driver to the linux kernel. Since I don't have experience with driver development and maybe it's not so appropriate to ask this... but would it be hard for me to write some code like what you did to get dualsense to work with ros? In which domains of knowledge do I need?

If not much prerequisites needed, I might have a try. Thanks ahead!

**Comment by naoki-mizuno** [comment]
All the heavy-lifting like communicating with the device and reading data is done by ds4drv, and unfortunately I don't know a whole lot about utilizing a device driver that comes with Linux. Although I imagine that the most difficult part about DualShock 4 was that the protocol was not open and people had to figure out what the bytes meant. Since that part can be handled by the official DualSense driver from Sony, my guess is that if you can figure out how to utilize the official driver it shouldn't be too difficult.

Sorry I can't be of much help! :(

**Comment by Hustwireless** [comment]
Thanks for the hint! It should already helped a lot!

**Comment by naoki-mizuno** [comment]
Great! I'll close this issue for now. Please feel free to reopen or create a new one if you have further questions/comments.
